# 1

## If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

## Find the sum of all the multiples of 3 or 5 below 1000.

In [4]:
def find_multiple_sum(nums):
    lst = []
    total = 0
    for num in nums:
        if num % 3 == 0:
            lst.append(num)
        if num % 5 == 0 and num not in lst:
            lst.append(num)
    for i in lst:
        total += i
    print(lst[:10])
    return total
nums = range(1000)
find_multiple_sum(nums)

[0, 3, 5, 6, 9, 10, 12, 15, 18, 20]

233168

# 2

## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [20]:
def fibonacci_even_sum(start):
    lst = start
    lst_2 = []
    tot = 0
    last = lst[-1]
    
    while last < 4000000:
            num = lst[-1]
            new = num + lst[-2]
            lst.append(new)
            last = new
    for x in lst:
        if x % 2 == 0:
            lst_2.append(x)
    for j in lst_2:
        tot += j
    return tot
        
start = [1, 2]
fibonacci_even_sum(start)

4613732

# 3

## The prime factors of 13195 are 5, 7, 13 and 29.

## What is the largest prime factor of the number 600851475143 ?

In [19]:
def max_prime_factor(number):
    not_prime = True
    divisor = []
    while not_prime == True:
        for num in range(1, number):
            if number % num == 0:
                not_prime = False
                divisor.append(num)
    return divisor
max_prime_factor(600851475143)

KeyboardInterrupt:

In [22]:
def max_prime_factor(number):
    divisor = []
    for num in range(2, number):
            if number % num == 0:
                divisor.append(num)
    return divisor
max_prime_factor(100)

[2, 4, 5, 10, 20, 25, 50]

In [42]:
def prime_factorization(number):
    divisor = []
    new_number = number
    for attempt in range(10000):
        for num in range(2,new_number + 1):
            if new_number % num == 0:
                divisor.append(num)
                new_number = int(new_number / divisor[-1])
                break
    return divisor[-1]
prime_factorization(600851475143)

6857

# 4

Find the largest palendrome that is created by multiplying two three digit numbers

In [57]:
def largest_three_pal():
    number_list_1 = []
    number_list_2 = []
    multiple_list = []
    palendrome_list = []
    palendrome_list_2 = []
    for num in range(100,1000):
        number_list_1.append(num)
        number_list_2.append(num)
    for num_1 in number_list_1:
        for num_2 in number_list_2:
            new = num_1 * num_2
            multiple_list.append(new)
    for n in multiple_list:
            n = str(n)
            if len(n) == 6:
                if n[0] is n[5] and n[1] is n[4] and n[2] is n[3]:
                    palendrome_list.append(n)
    for pal in palendrome_list:
        pal = int(pal)
        palendrome_list_2.append(pal)
    list.sort(palendrome_list_2)
    return palendrome_list_2[-1]
        
    
largest_three_pal()

906609

# 5

Find smallest number evenly divisible by all numbers from 1 to 20

In [64]:
def smallest_evenly_divisible():
    evenly_list = []
    divider_list = []
    for num in range(1,21):
        divider_list.append(num)
    for number in range(20,20000):
        modulo = False
        for num in divider_list:
            if number % num != 0:
                modulo = False
                break
            else:
                modulo = True
        if modulo == True:
                evenly_list.append(number)
    return evenly_list
smallest_evenly_divisible()

[]

# 6

Find difference between sum of squares and square of sum for numbers through 100

In [71]:
def squared_sum_diff():
    squared = []
    sm = 0
    squared_sum = 0
    sum_squared = 0
    for num in range(1,101):
        new = num ** 2
        squared.append(new)
    for sq in squared:
        sum_squared += sq
    for num in range(1,101):
        sm += num
    squared_sum = sm ** 2
    answer = squared_sum - sum_squared
    return answer
squared_sum_diff()

25164150

# 7

Find 10001th prime number

In [74]:
def ten_thousand_one_prime():
    prime_list = []
    number = 2
    while len(prime_list) < 10001:
        no_mod = 0
        while no_mod == 0:
            for num in range(2,number):
                mod = number % num
                if mod == 0:
                    no_mod += 1
                prime_list.append(number)
                no_mod = 0
        return(prime_list)
ten_thousand_one_prime()

KeyboardInterrupt:

# 8 
Find thirteen adjacent digits with largest product

In [111]:
# Convert to string and split... thousand = str
thousand = 7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450
thousand = str(thousand)
def thirteen_product(thousand):
    first_list = thousand
    product_list = []
    length = len(first_list)
    stop = length - 13
    print(stop)
    for i, num in enumerate(first_list):
        num = int(num)
        if i < stop:
            for n in range(2,13):
                num = num * int(first_list[i + n])
            product_list.append(num)
    return product_list
thirteen_product(thousand)

987

[1666980,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 233280,
 0,
 2099520,
 1224720,
 1088640,
 9797760,
 241920,
 6531840,
 3628800,
 5080320,
 50803200,
 71124480,
 31610880,
 94832640,
 27095040,
 39513600,
 28224000,
 42336000,
 14112000,
 76204800,
 9072000,
 28576800,
 9331200,
 36741600,
 31492800,
 20995200,
 56687040,
 113374080,
 340122240,
 408146688,
 181398528,
 2040733440,
 50388480,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 48988800,
 0,
 26127360,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 247726080,
 0,
 46448640,
 495452160,
 206438400,
 619315200,
 235929600,
 51609600,
 36864000,
 44236800,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 70543872,
 0,
 29393280,
 18662400,
 188956800,
 104976000,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 21432600,
 0,
 6123600,
 114307200,
 34992000,
 27216000,
 13996800,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 135475200,
 0,
 90316800,
 101606400,
 38707200,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 58786560,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 587865600,
 0,
 2090188800,
 2821754880,
 4702924800,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2304000,
 0,
 806400,
 483840,
 302400,
 241920,
 604800,
 725760,
 1814400,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 84672,
 0,
 84672,
 32256,
 28224,
 4032,
 12096,
 36288,
 145152,
 20736,
 145152,
 186624,
 497664,
 839808,
 2239488,
 3359232,
 2239488,
 2239488,
 3359232,
 26873856,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 9797760,
 0,
 13063680,
 1088640,
 5225472,
 5806080,
 9289728,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 141557760,
 0,
 106168320,
 123863040,
 123863040,
 278691840,
 104509440,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 702464,
 0,
 387072,
 12192768,
 6967296,
 48771072,
 31352832,
 768144384,
 493807104,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 82301184,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 560105280,
 0,
 210039480,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 12096000,
 0,
 13440000,
 24192000,
 13824000,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 836075520,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 564480,
 0,
 672000,
 504000,
 756000,
 2646000,
 13230000,
 1984500,
 8505000,
 53581500,
 53581500,
 428652000,
 42865200,
 300056400,
 900169200,
 420078960,
 1260236880,
 1568294784,
 1493614080,
 896168448,
 199148544,
 298722816,
 116169984,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 88179840,
 0,
 52254720,
 117573120,
 62705664,
 156764160,
 41803776,
 41803776,
 27869184,
 148635648,
 16515072,
 169869312,
 49545216,
 127401984,
 74317824,
 27869184,
 12386304,
 18579456,
 3096576,
 2322432,
 4064256,
 20321280,
 3810240,
 25401600,
 7408800,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 365783040,
 0,
 40642560,
 37324800,
 43545600,
 6912000,
 5184000,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 26880000,
 0,
 51609600,
 32256000,
 61931520,
 77414400,
 495452160,
 61931520,
 61931520,
 53084160,
 148635648,
 26542080,
 37158912,
 6193152,
 5419008,
 903168,
 451584,
 526848,
 4741632,
 5334336,
 1778112,
 10668672,
 14224896,
 4064256,
 28449792,
 5225472,
 73156608,
 20901888,
 23887872,
 13934592,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 69672960,
 0,
 104509440,
 26127360,
 29393280,
 6531840,
 3919104,
 1632960,
 279936,
 489888,
 69984,
 1119744,
 93312,
 124416,
 1866240,
 184320,
 9953280,
 552960,
 2580480,
 30965760,
 10321920,
 185794560,
 30965760,
 309657600,
 154828800,
 185794560,
 145152000,
 348364800,
 261273600,
 12441600,
 43545600,
 41472000,
 31104000,
 46656000,
 31104000,
 9720000,
 46656000,
 13996800,
 18144000,
 195955200,
 54432000,
 108864000,
 217728000,
 272160000,
 435456000,
 174182400,
 580608000,
 103219200,
 928972800,
 530841600,
 154828800,
 53084160,
 88473600,
 113246208,
 70778880,
 10616832,
 28311552,
 1769472,
 10616832,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 10800,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 62208000,
 0,
 37324800,
 99532800,
 8294400,
 6635520,
 4976640,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 768144384,
 0,
 256048128,
 260112384,
 113799168,
 167215104,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 77157360,
 0,
 66134880,
 51438240,
 132269760,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 11612160,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 41674500,
 27783000,
 50009400,
 20003760,
 9525600,
 40007520,
 11430720,
 36741600,
 85730400,
 4898880,
 13996800,
 156764160,
 7464960,
 89579520,
 52254720,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

# 9 

Find a Pythagorean triplet that adds to 1000

In [105]:
def find_thou_trip():
    trip_list = []
    for num in range (2,500):
        if num % 2 != 0:
            a = num
            b = ((a ** 2) - 1) / 2
            c = b + 1
            tot = a + b + c
            trip_list.append(tot)
    return trip_list
find_thou_trip()

[12.0,
 30.0,
 56.0,
 90.0,
 132.0,
 182.0,
 240.0,
 306.0,
 380.0,
 462.0,
 552.0,
 650.0,
 756.0,
 870.0,
 992.0,
 1122.0,
 1260.0,
 1406.0,
 1560.0,
 1722.0,
 1892.0,
 2070.0,
 2256.0,
 2450.0,
 2652.0,
 2862.0,
 3080.0,
 3306.0,
 3540.0,
 3782.0,
 4032.0,
 4290.0,
 4556.0,
 4830.0,
 5112.0,
 5402.0,
 5700.0,
 6006.0,
 6320.0,
 6642.0,
 6972.0,
 7310.0,
 7656.0,
 8010.0,
 8372.0,
 8742.0,
 9120.0,
 9506.0,
 9900.0,
 10302.0,
 10712.0,
 11130.0,
 11556.0,
 11990.0,
 12432.0,
 12882.0,
 13340.0,
 13806.0,
 14280.0,
 14762.0,
 15252.0,
 15750.0,
 16256.0,
 16770.0,
 17292.0,
 17822.0,
 18360.0,
 18906.0,
 19460.0,
 20022.0,
 20592.0,
 21170.0,
 21756.0,
 22350.0,
 22952.0,
 23562.0,
 24180.0,
 24806.0,
 25440.0,
 26082.0,
 26732.0,
 27390.0,
 28056.0,
 28730.0,
 29412.0,
 30102.0,
 30800.0,
 31506.0,
 32220.0,
 32942.0,
 33672.0,
 34410.0,
 35156.0,
 35910.0,
 36672.0,
 37442.0,
 38220.0,
 39006.0,
 39800.0,
 40602.0,
 41412.0,
 42230.0,
 43056.0,
 43890.0,
 44732.0,
 45582.0,
 46440.0,
 47306.0,
 48180.0,
 49062.0,
 49952.0,
 50850.0,
 51756.0,
 52670.0,
 53592.0,
 54522.0,
 55460.0,
 56406.0,
 57360.0,
 58322.0,
 59292.0,
 60270.0,
 61256.0,
 62250.0,
 63252.0,
 64262.0,
 65280.0,
 66306.0,
 67340.0,
 68382.0,
 69432.0,
 70490.0,
 71556.0,
 72630.0,
 73712.0,
 74802.0,
 75900.0,
 77006.0,
 78120.0,
 79242.0,
 80372.0,
 81510.0,
 82656.0,
 83810.0,
 84972.0,
 86142.0,
 87320.0,
 88506.0,
 89700.0,
 90902.0,
 92112.0,
 93330.0,
 94556.0,
 95790.0,
 97032.0,
 98282.0,
 99540.0,
 100806.0,
 102080.0,
 103362.0,
 104652.0,
 105950.0,
 107256.0,
 108570.0,
 109892.0,
 111222.0,
 112560.0,
 113906.0,
 115260.0,
 116622.0,
 117992.0,
 119370.0,
 120756.0,
 122150.0,
 123552.0,
 124962.0,
 126380.0,
 127806.0,
 129240.0,
 130682.0,
 132132.0,
 133590.0,
 135056.0,
 136530.0,
 138012.0,
 139502.0,
 141000.0,
 142506.0,
 144020.0,
 145542.0,
 147072.0,
 148610.0,
 150156.0,
 151710.0,
 153272.0,
 154842.0,
 156420.0,
 158006.0,
 159600.0,
 161202.0,
 162812.0,
 164430.0,
 166056.0,
 167690.0,
 169332.0,
 170982.0,
 172640.0,
 174306.0,
 175980.0,
 177662.0,
 179352.0,
 181050.0,
 182756.0,
 184470.0,
 186192.0,
 187922.0,
 189660.0,
 191406.0,
 193160.0,
 194922.0,
 196692.0,
 198470.0,
 200256.0,
 202050.0,
 203852.0,
 205662.0,
 207480.0,
 209306.0,
 211140.0,
 212982.0,
 214832.0,
 216690.0,
 218556.0,
 220430.0,
 222312.0,
 224202.0,
 226100.0,
 228006.0,
 229920.0,
 231842.0,
 233772.0,
 235710.0,
 237656.0,
 239610.0,
 241572.0,
 243542.0,
 245520.0,
 247506.0,
 249500.0]